#!/bin/bash

set -e

sudo mkdir /opt/ceh /nix
sudo chown $USER. /opt/ceh /nix
chmod 0700 /opt/ceh /nix
shopt -s dotglob
mv * /opt/ceh
cd /opt/ceh
# Travis already checks this out for us...
# git clone git://github.com/errge/ceh.git .
ln -s $HOME home
/opt/ceh/scripts/ceh-init.sh

sudo sh -c "cd /bin ; rm sh bash ; ln -s /nix/store/xhq72ynnh1ndmfyffp35b57kf31k0dq0-bash-4.2-p42/bin/bash sh ; ln -s /nix/store/xhq72ynnh1ndmfyffp35b57kf31k0dq0-bash-4.2-p42/bin/bash bash"
