* Guild for people who like Nix
+ Agreements and repositories for a shared GNU/Linux power-user environment.
+ So that it's easy to work on shared projects (e.g. the haskell
  header can be =#!/opt/ceh/bin/runhaskell=, instead of some
  complicated perl one-liner).
+ So that the packages are available with the same version on our
  machines (e.g. =emacs= and =ghc=).
+ These agreements are intentionally based on simple unifications
  instead of abstractions.
+ We use i686 Nix for package management and if you can decide the
  distribution that you use as a base system, we recommend i686 Debian
  (maybe with amd64 kernel, if you sometimes need the extra registers
  and stuff for your own programs).  But the point is that this should
  work on any modern GNU/Linux, we also tested Ubuntu lucid and precise.


* Requirements
+ Modern GNU/Linux distro (ubuntu, debian, etc.).
+ Intel architecture (i686 or amd64, no arm).
+ =sudo command= runs a command as root (so Debian guys will have to
  install sudo, Ubuntu guys are all set).  Root privileges is only
  used for initial installation to create the =/opt/ceh= and =/nix=
  directory and change the ownership of those to the user.  Root
  privileges are not needed for everyday usage and package
  installations.
+ =/etc/passwd= contains your user, so nix doesn't have to use any
  fancy NSS modules.
+ The user uses bash or zsh.  This is because he has to source
  /opt/ceh/scripts/nix-profile.sh which supports these two shells.
  Patches are welcome for other shells.


* Installation instructions
: sudo mkdir /opt/ceh
: sudo chown $USER. /opt/ceh
: chmod 0700 /opt/ceh
: cd /opt/ceh
: git clone git://github.com/errge/ceh.git .
: ln -s $HOME home
: /opt/ceh/scripts/nix-init.sh


* Everyday usage
In the =/opt/ceh/bin= directory there are small wrapper scripts.  Those
install the required pacakages for the wrapped binaries on first run.

=/opt/ceh/bin= is put into =$PATH= by =/opt/ceh/scripts/nix-profile.sh=,
that you're supposed to source from your =~/.bashrc=.

*** Exclusions: ignoring programs provided by ceh
If for any reason you prefer to ignore one of our provided binaries,
you can use the =ceh_exclude= script to create a symlink from
=/opt/ceh/bin-user/= to the other version of the binary in your PATH.

If you don't want the exclusion anymore, just delete the symlink.


* Installation of haskell packages with cabal
*** Pure haskell, non-FFI packages

The /opt/ceh/bin/ghc and /opt/ceh/bin/cabal scripts are wrapped in a
way that the whole toolchain (ghc, gcc, ld) is used from Nix.

This means that simple, non-FFI packages should just work out-of-the-box:
: cabal update
: vi ~/.cabal/config    (enable library-profiling if you want)
: cabal install hflags

*** FFI packages
For FFI packages to work, you of course need to have the required
clibs installed, so the package can FFI against it.  There is a
special nix profile where we keep all the clibs nix packages needed
for haskell compilations.  To install a new package to this profile
and then install the haskell package, do something like this:
: ceh_nixpkgs_install_for_ghc openssl 1.0pre23270_6f1aad7 4zvxbx66y0dsfil57ixgwzrvpxfcx8dg-openssl-1.0.0i.drv 9pn5796z6nz827inhq560zdispvkpzr8-openssl-1.0.0i
: cabal install HsOpenSSL


* TODOs
+ Have an LD_PRELOAD library that hides =/usr/lib/mozilla/plugins= from Firefox's view.


* Techtalk
: Title: Nix & ceh: reproducible power-user environment
:
: Abstract:
:
: It's common for engineers to use multiple GNU/Linux based computers
: daily, however it's not easy to achieve the same working environment
: on each of them.
:
: Computers owned by the company may run the company's linux variant,
: while computers at home run some common distribution.  Some of the
: running variants are already 64-bit, some are not.  Some of them is 2
: years old, some of them is fresh.
:
: On top of this mixture, it's hard to imagine to run exactly the same
: version of GNU Emacs or Mozilla Firefox (with all the hard to install
: plugins: flash, googletalk, java), without installing a common base
: operating system.
:
: This is the problem that I wanted a solution for, when I looked into
: the Nix package manager and the Nixpkgs package collection.  After a
: month of exploration I now have a working setup (called ceh), that I
: run on all of my computers to synchronize (via Git) the choice of
: software between them.
:
: In the techtalk I will present the fundamentals of Nix and show ceh,
: my setup around Nix.

* Design ideas for V2
** What issues do we have
*** More consistent nixpkgs version for different packages
Currently ceh_nixpkgs_install supports using different nixpkgs
versions for every executable.  It's so efficient in what it does,
that we don't care at all about using the same nixpkgs in different
packages.

This seems to be working alright, but it's definitely responsible for
the pretty big usage of disk space in /nix/store.

It'd be nice to have some baseline nixpkgs version that all the easy
packages use: emacs, coq, androidsdk, ghc, python3, tmux, etc.  And
we'd only use newer nixpkgs version for packages that have to be new:
e.g. firefox, coursera-dl.  Of course we'd move the baseline quite
frequently, so we keep ourselves generally fresh (e.g. every 3
months?).

*** All these hashes are a bit painful to have
We know, that nixpkgs_version+package_name+$NIXPKGS_CONFIG determines
the derivation and the output hash, so we only include those hashes to
catch an inconsistency when the result of this mapping is not
consistent with previous results on other machines.

This never have actually happened to anyone, I know.

Therefore maybe it's a bit too much work we do to achieve this
unneeded extra safety.  We definitely don't need both hashes, having
the derivation hash is totally superfluous.

If we decide to get rid of both hashes, then we still should have a
log file with the installations done or maybe a command to list all
the ceh installed packages with hashes, so users can compare there
machines to debug issues.

** Missing features
*** Easy upgradability for packages
Let's assume that I'm willing to spend 2 minutes now to try out if
tmux works even with a newer nixpkgs (the next baseline, or whatever).
It'd be nice to have some environment variable that the user can
switch and will result in all installations trying to use some new
nixpkgs version.  After the user tests that everything works, she
should see the needed {hash, nixpkgs version, etc.} changes in
git status /opt/ceh.  So if everything works she would just have to
git commit.

Since some packages have version in their name (e.g. firefox20Wrapper
or haskellPackages_ghc762.ghc), this won't be ever totally automatic,
but in those cases at least the user will notice when ceh is using
some packages that are not even there in newer nixpkgs.

*** Install world
Installation of all the packages currently found anywhere in /opt/ceh.
Without starting the installed programs of course.

I see two use cases for this.

First, on demand installs are very cool, but if you are going out to
have dinner anyways, than installing everything now and just using
your new machine when you come back is even better.

Second, we would have a way to test the whole system to see if stuff
can still get installed.  We could run this on a server every day or
so (and export the resulting hashes if we decide to get rid of those
on normal usage, so users will have something to compare their
machines to).
