* Nix szeretok cehe
+ Közös megállapodások és repositoryk a linuxos fejlesztői környezeteinkről.
+ Hogy könnyű legyen mindenkinél működő programokat írni.
  - Pl. haskell header lehessen `#!/opt/ceh/bin/runhaskell' bonyolítás helyett.
+ Hogyha a hasznos csomagok mindenkinél fel legyenek telepítve.
  - Pl. ghc.
+ A megállapodások szándékosan minél egyszerűbb unifikációra
  törekszenek, nem absztrakcióra.
+ nix-et használunk package managementre, mert úgy tűnik, hogy meg
  lehet vele oldani egyszerűen bináris csomagok pontos repródukálását
  vegyes linuxok között.
+ a nix-ünk i686 és azt ajánljuk, hogy a gépeinken is i686 legyen a
  debian.  Ez nem követelmény és továbbá ajánlott az i686 debiant
  amd64 kernellel használni (ami tökéletesen működik), hogy lehetővé
  váljon esetenként amd64 kódok futtatása, ha a performance igényli.


* Requirements
+ Valamilyen értelmes linux (gubuntu, debian, ubuntu).
+ Intel architektúra (i686 vagy amd64, no arm please).
+ `sudo parancs' rootként futtat parancsot (tehát debianosoknak
  telepíteni kell a sudo-t)


* Inicializálás
sudo mkdir /opt/ceh
sudo chown $USER. /opt/ceh
chmod 0700 /opt/ceh
cd /opt/ceh
git clone git://github.com/errge/ceh.git .
#  (if you want to contribute and you have a github user: git@github.com:errge/ceh.git)
ln -s $HOME home


* Nix telepítés
/opt/ceh/scripts/nix-init.sh


* Nix használat
** Az /opt/ceh/bin-ben levő binárisok beszerzése új gépen
A /opt/ceh/bin-ben symlinkek vannak kizárólag a /nix/store/...-ra.
Egy új gépen természetesen ezek törött symlinkek, azonban a nix be
tudja szerezni őket a hashük alapján, ennek a módja:

nix-env -i /opt/ceh/bin/emacs

Avagy ha nagyon magabiztosak vagyunk:
for i in /opt/ceh/bin/* ; do nix-env -i $i ; done


* Haskell csomagok forditasa cabal-lal
Van a nix-nek technologiaja a ghc meghackelesere, hogy a cabal
csomagokat is o kezelje, de ehhez karbantartanak config fileokat, amik
a cabal csomagokat irjak le egyesevel.  Ez azt jelenti, hogy
laggolnank a hackagehez kepest es plusz bonyolitasokat kellene
felvallalnunk.  Az ut, amit megprobalunk az inkabb az, hogy a cabal-t
onmagaban hasznaljuk haskell libek feltelepitesehez, nem a nix-en
keresztul.

Eloszor allitsuk be, hogy kerunk library profiling-ot:
  cabal
  vi ~/.cabal/config (es engedelyezni a library-profiling-ot)

Mivel a nix (i386) architekturaja elterhet a gep (amd64)
architekturajatol, az egesz toolchainbol a nix-et akarjuk hasznalni,
nem csak ghc-bol.  Tehat ld, gcc, g++, minden.  Ezt erik el a
/opt/ceh/bin-ben levo kis wrapper scriptek, ami cabal, ghci, ghc,
stb. futtatasa eseten megmachinaljak a PATH-t, CFLAGS-t, LDFLAGS-t oly
modon, hogy ne a distrib binutils-a legyen hasznalva, hanem a nix-e.

Ez azt jelenti, hogy egyszeru, FFI mentes haskell csomagok telepitese
egyszeruen out-of-the-box mukodik (cabal install whatever).

FFI csomagok eseten termeszetesen szukseges elotte feltelpiteni a
~/.nix-profile-unkba a "-dev csomagokat", pl.:
  nix-env -i nixpkgs.xlibs.libX11

Nehezseget okoz, hogy megtudjuk ezeket a neveket, ebben
tamaszkodhatunk a nix mar meglevo csomaggyujtemenyere es
kiturkalhatjuk onnan.  Mindenesetre ez meg tovabbi kutatast igenyel,
hogy igazan kenyelmes legyen.

* TODO-k
** README.org formazas githubbal
Kitalalni, hogy hogyan kell org mode-ot es github readmet egyutt
hasznalni, hogy a formazasa a kod szegmenseknek <pre> legyen...
